# $File: .travis.yml,v 1.6 2014/03/10 12:42:49 kim Exp $
language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq automake libtool make python zlib1g-dev
script:
 - autoreconf -f -i
 - ./configure --disable-silent-rules
 - make -j4
 - make -C tests check
